using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApp3
{
    /*
    class ExceptionSample
    {
        static void Main(String [] args)
        {
            // Demonstrating try catch finally samples.
            try
            {
                int[] a = { 1,2,3,4,5};
                Console.WriteLine("The length of the array is " + a.Length);
               

                //accessing out of range array
                Console.WriteLine(a[5]);
                //Console.ReadLine();
            }
            catch(Exception e)
            {
                //Console.WriteLine(e.Message);
                //Console.ReadLine();
                throw;
            }
            finally
            {

            }
        }
    }
    */
}
